# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Build@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure for Students (3e62f9fd-92d4-4ce8-8b24-f8408660c2e7)'
        azureContainerRegistry: '{"loginServer":"codeexecuter.azurecr.io", "id" : "/subscriptions/3e62f9fd-92d4-4ce8-8b24-f8408660c2e7/resourceGroups/OutOfMemoryError/providers/Microsoft.ContainerRegistry/registries/codeExecuter"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'build'
      env:
        SU_PASSWORD: $(SU_PASSWORD)
    - task: Push@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure for Students (3e62f9fd-92d4-4ce8-8b24-f8408660c2e7)'
        azureContainerRegistry: '{"loginServer":"codeexecuter.azurecr.io", "id" : "/subscriptions/3e62f9fd-92d4-4ce8-8b24-f8408660c2e7/resourceGroups/OutOfMemoryError/providers/Microsoft.ContainerRegistry/registries/codeExecuter"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'push'
      env:
        SU_PASSWORD: $(SU_PASSWORD)

